

services:
  mqtt-broker:
    image: emqx/emqx:latest
    container_name: mqtt-broker
    ports:
      - "1883:1883"     
      - "8083:8083"   
      - "18083:18083"   
    restart: always

  ms1:
    build: ./MS1
    container_name: ms1
    depends_on:
      - mqtt-broker
    ports:
      - "8000:8000"  
      - "8080:8080"   
    restart: always

  ms2:
    build: ./MS2
    container_name: ms2
    depends_on:
      - mqtt-broker
    restart: always